services:
  eureka-service:
    image: eureka-service
    build: ./Eureka
    ports:
      - "8761:8761"
    networks:
      - app-network
  gateway-service:
    image: gateway-service
    build: ./Gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - eureka-service
  security-service:
    image: security-service
    build: ./security-service
    ports:
      - "8083:8083"
    networks:
      - app-network
    depends_on:
      - eureka-service
      - gateway-service
  books-service:
    image: books-service
    build: ./Book
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - eureka-service
      - gateway-service
  authors-service:
    image: authors-service
    build: ./Author
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - eureka-service
      - gateway-service

networks:
  app-network:
