server:
  port: 8080  # Port for the gateway

spring:
  application:
    name: api-gateway  # Name of the gateway service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery for routing
          lower-case-service-id: true  # Ensure service IDs are lowercase for routing
      routes:
        - id: books-service
          uri: http://books-service:8081  # Load balancing to books-service
          predicates:
            - Path=/books/**  # Route requests with /books/ to the Books service
          filters:
            - name: AuthenticationFilter
        - id: authors-service
          uri: http://authors-service:8082  # Load balancing to authors-service
          predicates:
            - Path=/authors/**  # Route requests with /authors/ to the Authors service
          filters:
            - name: AuthenticationFilter
        - id: security-service
          uri: http://security-service:8083  # Load balancing to security-service
          predicates:
            - Path=/auth/**  # Route requests with /auth/ to the Security service
          filters:
            - name: AuthenticationFilter


eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/  # Eureka server URL
