spring:
  data:
    mongodb:
      uri: mongodb+srv://josephmartin3112:123456joseph7890@trialproject.wigju.mongodb.net/books?retryWrites=true&w=majority&appName=TrialProject
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/ # URL of the Eureka server
    fetch-registry: true
    register-with-eureka: true


