spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/books
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server
    fetch-registry: true
    register-with-eureka: true


